### ISSUE TITLE
Which document is the correct?

### ISSUE THREAD

**Issue by florianmulatz** [srg74/WLED-wemos-shield#43]
Hi,

To be honest, I don't know my way around anymore.
There are different BOMs and different PCBs in the repository.
I have ordered the v2 of the PCB and the bare-mininum parts of the BOM v1.3, but now seems not to fit perfectly.

Please info what is correct now - which BOM belongs to which PCB and maybe then I could help updating the soldering instructions. I'm not sure if the thing should work now.

And the Bare-Minimum list tells R8 - where should this one go? I don't find it on PCB. thx

**Comment by srg74** [comment]
Don’t worry, everything is fixable. Schematic and BOM is not changed a lot since version 0.93. Difference between versions is more functionality and convenience. Recent BOM pdf is good for ordering parts. They will fit on all versions. Only one “big” difference from previous versions is headers 10x2 female. But it obvious if you just look at PCB. If you have a further question it’s quicker when you ask at WLED Discord. I can answer you there in real time.
