### ISSUE TITLE
questions for v3.0 board revision

### ISSUE THREAD

**Issue by dakky** [srg74/WLED-wemos-shield#94]
* which version is delivered when ordering via pcbways? 
  the image on pcbway says 3.0 but the lvlshifter is not a smd one, which conflict with the images of 3.0 here in this repo:
  https://github.com/srg74/WLED-wemos-shield/tree/master/resources/universal_shield
* if v3.0: Will the wiki (Assembly) be updated to v3.0?
* if v3.0: why the switch to SMD parts? The "easy to assemble"-feature seems deprecated this way
* if <v3.0: which BOM is needed for the version delivered by pcbways?

**Comment by srg74** [comment]
On this GitHub page is only a one DIY board. You see mix because I also providing fully assembled SMD boards. You have to follow https://github.com/srg74/WLED-wemos-shield/wiki to assemble DIY board. BOM file exist only for TH parts.
Difference in v2.1 and v3.0 is only added circuit for PWM fan so basically most of all assembly guide is still good.

**Comment by dakky** [comment]
so https://github.com/srg74/WLED-wemos-shield/blob/master/resources/BOM/BOM_v3.0.pdf is the BOM to go with?

**Comment by srg74** [comment]
Yes and please read carefully wiki for the options. You might want minimum configuration, but not every possible feature.

**Comment by dakky** [comment]
yes it will be the minimum one. thanks for your support.
